# Generated by Django 3.1.7 on 2021-04-17 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('hobby', models.CharField(max_length=30)),
                ('profilepic', models.ImageField(upload_to='')),
                ('password', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'signup',
            },
        ),
        migrations.CreateModel(
            name='Recoverdata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('secret_code', models.CharField(default=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], max_length=10)),
                ('uid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recnewdb', to='account.signup')),
            ],
        ),
    ]
