# Generated by Django 3.0.3 on 2020-04-18 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='questions',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_asker', to='signup.signup')),
            ],
            options={
                'db_table': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='answers',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('auid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answerer', to='signup.signup')),
                ('question_to_answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_to_answer', to='questions.questions')),
            ],
            options={
                'db_table': 'Answers',
            },
        ),
    ]
