# Generated by Django 3.0.3 on 2020-04-20 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
        ('questions', '0013_auto_20200420_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='likes',
        ),
        migrations.AlterField(
            model_name='answers',
            name='auid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answerer', to='signup.Signup'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='question_to_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_to_answer', to='questions.Questions'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='quid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_asker', to='signup.Signup'),
        ),
        migrations.CreateModel(
            name='QuestionLike',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('Qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_liked', to='questions.Questions')),
                ('luid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Qliker', to='signup.Signup')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
    ]
