# Generated by Django 3.0.3 on 2020-04-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_auto_20200421_1900'),
        ('questions', '0019_auto_20200422_1646'),
    ]

    operations = [
    ]
