# Generated by Django 3.0.5 on 2020-04-29 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0028_auto_20200426_1825'),
        ('questions', '0024_auto_20200428_1846'),
    ]

    operations = [
    ]
