# Generated by Django 3.0.6 on 2020-06-08 16:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_auto_20200604_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='location',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='pnumber',
        ),
        migrations.AlterField(
            model_name='signup',
            name='profilepic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
