# Generated by Django 3.0.6 on 2020-05-14 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0003_auto_20200514_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='recoverdata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('secret_code', models.CharField(default=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], max_length=10)),
                ('uid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recnewdb', to='signup.Signup')),
            ],
        ),
    ]
