# Generated by Django 3.0.3 on 2020-04-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_sender', models.EmailField(max_length=40)),
                ('feedback', models.TextField(default='', max_length=400)),
            ],
        ),
    ]
