# Generated by Django 3.0.5 on 2020-05-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_sender', models.EmailField(max_length=40)),
                ('feedback', models.TextField(default='', max_length=400)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'FeedBack',
            },
        ),
    ]
