# Generated by Django 3.0.3 on 2020-04-30 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='FeedBack',
        ),
    ]
