# Generated by Django 3.0.5 on 2020-05-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
