# Generated by Django 3.1.7 on 2021-04-17 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1025)),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(default='Python', max_length=15)),
                ('quid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_asker', to='account.signup')),
            ],
            options={
                'db_table': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionLike',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('Qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_liked', to='QandA.questions')),
                ('luid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Qliker', to='account.signup')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=255)),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('auid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answerer', to='account.signup')),
                ('question_to_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_to_answer', to='QandA.questions')),
            ],
            options={
                'db_table': 'Answers',
            },
        ),
    ]
