# Generated by Django 3.0.3 on 2020-04-19 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('text_time', models.DateTimeField(auto_now_add=True)),
                ('text_message', models.CharField(default='', max_length=255)),
                ('r1uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_user', to='signup.Signup')),
                ('r2uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_user', to='signup.Signup')),
            ],
        ),
    ]
