# Generated by Django 3.0.6 on 2020-05-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_sender',
            field=models.EmailField(default='Anornymous@gmail.com', max_length=40),
        ),
    ]
