# Generated by Django 3.0.5 on 2020-04-20 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0005_auto_20200420_1408'),
        ('chatroom', '0008_auto_20200420_1244'),
    ]

    operations = [
    ]
