# Generated by Django 3.0.3 on 2020-04-20 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0010_auto_20200420_1938'),
        ('chatroom', '0016_auto_20200420_1616'),
    ]

    operations = [
    ]
