# Generated by Django 3.0.5 on 2020-04-22 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0014_auto_20200422_1646'),
        ('chatroom', '0019_auto_20200421_1900'),
    ]

    operations = [
    ]
