# Generated by Django 3.0.5 on 2020-04-30 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0033_auto_20200430_1023'),
        ('chatroom', '0029_auto_20200428_1551'),
    ]

    operations = [
    ]
